lawrence@laptop:~/Desktop/sde_project$ python3 telegram_flask.py
 * Serving Flask app "telegram_flask" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 970-589-543
127.0.0.1 - - [06/Sep/2020 00:18:03] "GET /start HTTP/1.1" 200 -
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/lawrence/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/lawrence/.local/lib/python3.6/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "/home/lawrence/Desktop/sde_project/telegram_flask.py", line 64, in list_languages
    languages = res.text()
TypeError: 'str' object is not callable
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/lawrence/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/lawrence/.local/lib/python3.6/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "/home/lawrence/Desktop/sde_project/telegram_flask.py", line 41, in dest_language
    lang = context.args[0]  # ['it'] -> 'it'
IndexError: list index out of range
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/lawrence/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/lawrence/.local/lib/python3.6/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "/home/lawrence/Desktop/sde_project/telegram_flask.py", line 36, in translate
    translated = res.json()['response']
  File "/home/lawrence/.local/lib/python3.6/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

